// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: baseCommand.proto

package com.laoxin.mq.protos;

public final class BaseCommandProto {
  private BaseCommandProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BaseCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BaseCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *命令类型
     * </pre>
     *
     * <code>int32 commandType = 1;</code>
     */
    int getCommandType();

    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>bytes message = 15;</code>
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code BaseCommand}
   */
  public  static final class BaseCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BaseCommand)
      BaseCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseCommand.newBuilder() to construct.
    private BaseCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseCommand() {
      commandType_ = 0;
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              commandType_ = input.readInt32();
              break;
            }
            case 122: {

              message_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.laoxin.mq.protos.BaseCommandProto.internal_static_BaseCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.laoxin.mq.protos.BaseCommandProto.internal_static_BaseCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.laoxin.mq.protos.BaseCommandProto.BaseCommand.class, com.laoxin.mq.protos.BaseCommandProto.BaseCommand.Builder.class);
    }

    public static final int COMMANDTYPE_FIELD_NUMBER = 1;
    private int commandType_;
    /**
     * <pre>
     *命令类型
     * </pre>
     *
     * <code>int32 commandType = 1;</code>
     */
    public int getCommandType() {
      return commandType_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 15;
    private com.google.protobuf.ByteString message_;
    /**
     * <pre>
     *消息
     * </pre>
     *
     * <code>bytes message = 15;</code>
     */
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commandType_ != 0) {
        output.writeInt32(1, commandType_);
      }
      if (!message_.isEmpty()) {
        output.writeBytes(15, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (commandType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandType_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.laoxin.mq.protos.BaseCommandProto.BaseCommand)) {
        return super.equals(obj);
      }
      com.laoxin.mq.protos.BaseCommandProto.BaseCommand other = (com.laoxin.mq.protos.BaseCommandProto.BaseCommand) obj;

      boolean result = true;
      result = result && (getCommandType()
          == other.getCommandType());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCommandType();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.laoxin.mq.protos.BaseCommandProto.BaseCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BaseCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BaseCommand)
        com.laoxin.mq.protos.BaseCommandProto.BaseCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.laoxin.mq.protos.BaseCommandProto.internal_static_BaseCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.laoxin.mq.protos.BaseCommandProto.internal_static_BaseCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.laoxin.mq.protos.BaseCommandProto.BaseCommand.class, com.laoxin.mq.protos.BaseCommandProto.BaseCommand.Builder.class);
      }

      // Construct using com.laoxin.mq.protos.BaseCommandProto.BaseCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        commandType_ = 0;

        message_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.laoxin.mq.protos.BaseCommandProto.internal_static_BaseCommand_descriptor;
      }

      @java.lang.Override
      public com.laoxin.mq.protos.BaseCommandProto.BaseCommand getDefaultInstanceForType() {
        return com.laoxin.mq.protos.BaseCommandProto.BaseCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.laoxin.mq.protos.BaseCommandProto.BaseCommand build() {
        com.laoxin.mq.protos.BaseCommandProto.BaseCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.laoxin.mq.protos.BaseCommandProto.BaseCommand buildPartial() {
        com.laoxin.mq.protos.BaseCommandProto.BaseCommand result = new com.laoxin.mq.protos.BaseCommandProto.BaseCommand(this);
        result.commandType_ = commandType_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.laoxin.mq.protos.BaseCommandProto.BaseCommand) {
          return mergeFrom((com.laoxin.mq.protos.BaseCommandProto.BaseCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.laoxin.mq.protos.BaseCommandProto.BaseCommand other) {
        if (other == com.laoxin.mq.protos.BaseCommandProto.BaseCommand.getDefaultInstance()) return this;
        if (other.getCommandType() != 0) {
          setCommandType(other.getCommandType());
        }
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.laoxin.mq.protos.BaseCommandProto.BaseCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.laoxin.mq.protos.BaseCommandProto.BaseCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int commandType_ ;
      /**
       * <pre>
       *命令类型
       * </pre>
       *
       * <code>int32 commandType = 1;</code>
       */
      public int getCommandType() {
        return commandType_;
      }
      /**
       * <pre>
       *命令类型
       * </pre>
       *
       * <code>int32 commandType = 1;</code>
       */
      public Builder setCommandType(int value) {
        
        commandType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *命令类型
       * </pre>
       *
       * <code>int32 commandType = 1;</code>
       */
      public Builder clearCommandType() {
        
        commandType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>bytes message = 15;</code>
       */
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>bytes message = 15;</code>
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息
       * </pre>
       *
       * <code>bytes message = 15;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BaseCommand)
    }

    // @@protoc_insertion_point(class_scope:BaseCommand)
    private static final com.laoxin.mq.protos.BaseCommandProto.BaseCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.laoxin.mq.protos.BaseCommandProto.BaseCommand();
    }

    public static com.laoxin.mq.protos.BaseCommandProto.BaseCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseCommand>
        PARSER = new com.google.protobuf.AbstractParser<BaseCommand>() {
      @java.lang.Override
      public BaseCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.laoxin.mq.protos.BaseCommandProto.BaseCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BaseCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BaseCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021baseCommand.proto\"3\n\013BaseCommand\022\023\n\013co" +
      "mmandType\030\001 \001(\005\022\017\n\007message\030\017 \001(\014B(\n\024com." +
      "laoxin.mq.protosB\020BaseCommandProtob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BaseCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BaseCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BaseCommand_descriptor,
        new java.lang.String[] { "CommandType", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
