server:
  port: ${SERVER_PORT:7000}
spring:
  application:
    name: lx-mq-broker
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      url: ${SPRING_DATASOURCE_URL:jdbc:mysql://www.laoxin.com:3306/poseidon_mq?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true}
      username: ${SPRING_DATASOURCE_USERNAME:root}
      password: ${SPRING_DATASOURCE_PASSWORD:root}
      initial-size: 1 #连接池初始化大小
      min-idle: 2 #最小空闲连接数
      max-active: 5 #最大连接数
      max-wait: 60000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1 FROM DUAL

#############################################################################
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/**/*.xml
  type-aliases-package: com.laoxin.mq.broker.entity
#############################################################################
mq:
  serverPort: ${MQ_SERVER_PORT:17000}
  messageStoreType: rdb
  metaStoreType: rdb
  consumerQueueThresholdSzie: 512
  defaultPushSize: 10
  readMessageThreads: 50
  pushMessageThreads: 20
  enableMonitor: true
  enableTrace: true

#############################################################################